version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongoroot
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ENABLE_AUTH: "true"
    secrets:
      - mongo_root_password
      - mongo_app_password

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://appuser:mongopass@mongo:27017
      DEPLOY_MODE: docker
    depends_on:
      - mongo

  scheduler:
    build:
      context: .
      dockerfile: scheduler/Dockerfile.scheduler
    environment:
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017
      DEPLOY_MODE: docker
    depends_on:
      - mongo

volumes:
  mongo_data:

secrets:
  mongo_root_password:
    file: ./secrets/mongo_root_password
  mongo_app_password:
    file: ./secrets/mongo_app_password
