services:
  mongo:
    image: mongo:6.0.12
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: admin
    healthcheck:
      test: ["CMD", "mongosh", "--host", "mongo", "--eval", "db.adminCommand('ping')", "--username", "admin", "--password", "admin123", "--authenticationDatabase", "admin", "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: bitnami/kafka:3.4
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - ./kafka_data:/bitnami/kafka  # Kafka数据持久化目录
    environment:
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092  # 重要！需要改为容器名称
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"  # 允许明文通信
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 10

  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    volumes:
      - ./zookeeper_data:/bitnami/zookeeper  # Zookeeper数据持久化目录
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "zkServer.sh", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
  

  # api:
  #   build:
  #     context: .
  #     dockerfile: api/Dockerfile
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     MONGO_URI: mongodb://appuser:appuser123@mongo:27017/taskdb?authSource=admin&retryWrites=true&w=majority&connectTimeoutMS=5000
  #     DEPLOY_MODE: docker
  #   depends_on:
  #     - mongo

  # scheduler:
  #   build:
  #     context: .
  #     dockerfile: scheduler/Dockerfile.scheduler
  #   environment:
  #     MONGO_URI: mongodb://appuser:appuser123@mongo:27017/taskdb?authSource=admin&retryWrites=true&w=majority
  #     KUBECONFIG: ~/.kube/config
  #   volumes:
  #     - ~/.kube:~/.kube
  #     - ~/.minikube:~/.minikube
  #     - /etc/localtime:/etc/localtime:ro
  #     - /etc/timezone:/etc/timezone:ro
  #   depends_on:
  #     mongo:
  #       condition: service_healthy

volumes:
  mongo_data:  # MongoDB的卷声明（已存在）
  kafka_data:   # 新增Kafka卷声明
  zookeeper_data: # 新增Zookeeper卷声明