apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-api
  template:
    metadata:
      labels:
        app: task-api
    spec:
      containers:
      - name: task-api
        image: neuroengine/task-api:latest
        env:
        - name: API_PORT
          value: "5000"
        ports:
        - containerPort: 5000
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/"
---
apiVersion: v1
kind: Service
metadata:
  name: task-api
spec:
  selector:
    app: task-api
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: task-api-ingress
spec:
  rules:
  - host: task-api.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: task-api
            port:
              number: 80
