apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-scheduler
  template:
    metadata:
      labels:
        app: task-scheduler
    spec:
      serviceAccountName: task-scheduler-sa
      containers:
      - name: scheduler
        image: neuroengine/task-scheduler:latest
        env:
        - name: SCHEDULER_PORT
          value: "5050"  # 使用与API服务不同的端口范围
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/"
        ports:
        - containerPort: 5050
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-scheduler-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-manager
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: task-scheduler-job-manager
subjects:
- kind: ServiceAccount
  name: task-scheduler-sa
roleRef:
  kind: Role
  name: job-manager
  apiGroup: rbac.authorization.k8s.io
